DROP TABLE STUDENT;
DROP TABLE PROFESSOR;
DROP TABLE MAJOR;

CREATE TABLE PROFESSOR(
    PROF_NO NUMBER(2) PRIMARY KEY,
    PROF_NAME VARCHAR2(20 BYTE),
    MAJOR_NO NUMBER(2));
    
CREATE TABLE MAJOR(
    MAJOR_NO NUMBER(2) PRIMARY KEY,
    MAJOR_NAME VARCHAR2(20 BYTE));
    
CREATE TABLE STUDENT(
    STU_NO NUMBER PRIMARY KEY,
    STU_NAME VARCHAR2(20 BYTE),
    MARK NUMBER(3,2), -- 1.00 ~9.99
    MAJOR_NO NUMBER(2),
    PROF_NO NUMBER(2));
    
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PROFESSOR_FK FOREIGN KEY(PROF_NO) REFERENCES PROFESSOR(PROF_NO) ON DELETE CASCADE;
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_MAJOR_FK FOREIGN KEY(MAJOR_NO) REFERENCES MAJOR(MAJOR_NO) ON DELETE CASCADE;